---

authtwitter-linkback:
  path: /linkback
  defaults: {
    _controller: 'SimpleSAML\Module\authtwitter\Controller\Twitter::linkback'
  }
  methods: [GET]

authtwitter-linkback-legacy:
  path: /linkback.php
  defaults: {
    _controller: 'SimpleSAML\Module\authtwitter\Controller\Twitter::linkback'
  }
  methods: [GET]
